#!/usr/bin/env node
// Copies the compiled ABIs from contracts/out into src/contracts/abis/*.ts.
// Run after `forge build` in ./contracts: `pnpm abis`.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(new URL('..', import.meta.url).pathname)
const targets = [
  { artifact: 'StripVault.sol/StripVault.json', file: 'StripVault.ts', name: 'stripVaultAbi' },
  { artifact: 'MultiplierAccountant.sol/MultiplierAccountant.json', file: 'MultiplierAccountant.ts', name: 'multiplierAccountantAbi' },
  { artifact: 'IStockToken.sol/IStockToken.json', file: 'StockToken.ts', name: 'stockTokenAbi' },
  { artifact: 'HalveToken.sol/HalveToken.json', file: 'HalveToken.ts', name: 'halveTokenAbi' },
]

for (const t of targets) {
  const src = resolve(root, 'contracts/out', t.artifact)
  const { abi } = JSON.parse(readFileSync(src, 'utf8'))
  const body = JSON.stringify(abi, null, 2)
  const out = `// Generated by scripts/sync-abis.mjs from contracts/out/${t.artifact}. Do not edit by hand.\nexport const ${t.name} = ${body} as const\n`
  writeFileSync(resolve(root, 'src/contracts/abis', t.file), out)
  console.log(`wrote src/contracts/abis/${t.file} (${abi.length} entries)`)
}
